export const homeObjOne={
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextdesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo={
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextdesc: false,
    topLine: 'Unlinited Access',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'piggy bank',
    dark: false,
    primary: false,
    darkText: true,
}
export const homeObjThree={
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextdesc: false,
    topLine: 'Join Our Team',
    headline: 'Creating an account is extremely easy',
    description: "Get everything set up and ready in under 10 minutes. All you need to do is add your information and you're ready to global.",
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg-5.svg').default,
    alt: 'paper',
    dark: false,
    primary: false,
    darkText: true,
}