export const homeObjOne={
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextdesc: true,
    topLine: 'Whatsapp Invitation',
    headline: 'Automatic whatsapp messages',
    description: 'We will send invitations through whatsapp to all your relatives as a remainder.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo={
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextdesc: false,
    topLine: 'Website',
    headline: 'Page in our website',
    description: 'We will add a page in our webiste with all details of the ceremony to help visitors ',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'piggy bank',
    dark: false,
    primary: false,
    darkText: true,
}
export const homeObjThree={
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextdesc: false,
    topLine: 'Support',
    headline: 'Active Support to all relatives',
    description: "We will help all your relatives to reach their destination on time without any hassle.",
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt: 'paper',
    dark: false,
    primary: false,
    darkText: true,
}